//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  entry: Entry;
  entryConnection: EntryConnection;
  about: About;
  aboutConnection: AboutConnection;
  contact: Contact;
  contactConnection: ContactConnection;
  home: Home;
  homeConnection: HomeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEntryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEntryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EntryFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};

export type DocumentFilter = {
  entry?: InputMaybe<EntryFilter>;
  about?: InputMaybe<AboutFilter>;
  contact?: InputMaybe<ContactFilter>;
  home?: InputMaybe<HomeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Entry | About | Contact | Home | Folder;

export type Entry = Node & Document & {
  __typename?: 'Entry';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  summary: Scalars['String']['output'];
  contentType: Scalars['String']['output'];
  section?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  tag?: Maybe<Scalars['String']['output']>;
  kicker?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  readTime?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  tags: Array<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  stack?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  status?: Maybe<Scalars['String']['output']>;
  repo?: Maybe<Scalars['String']['output']>;
  demo?: Maybe<Scalars['String']['output']>;
  highlights?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EntryFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  summary?: InputMaybe<StringFilter>;
  contentType?: InputMaybe<StringFilter>;
  section?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  kicker?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  readTime?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  tags?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  featured?: InputMaybe<BooleanFilter>;
  stack?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  repo?: InputMaybe<StringFilter>;
  demo?: InputMaybe<StringFilter>;
  highlights?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type EntryConnectionEdges = {
  __typename?: 'EntryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Entry>;
};

export type EntryConnection = Connection & {
  __typename?: 'EntryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EntryConnectionEdges>>>;
};

export type AboutHero = {
  __typename?: 'AboutHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  terminalText?: Maybe<Scalars['String']['output']>;
};

export type AboutOverviewPaths = {
  __typename?: 'AboutOverviewPaths';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
};

export type AboutOverview = {
  __typename?: 'AboutOverview';
  quote?: Maybe<Scalars['String']['output']>;
  paths?: Maybe<Array<Maybe<AboutOverviewPaths>>>;
  bridgeText?: Maybe<Scalars['String']['output']>;
};

export type AboutVision = {
  __typename?: 'AboutVision';
  statement?: Maybe<Scalars['String']['output']>;
  eyebrow?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type AboutManifesto = {
  __typename?: 'AboutManifesto';
  watermark?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  lines?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  quote?: Maybe<Scalars['String']['output']>;
};

export type AboutFooter = {
  __typename?: 'AboutFooter';
  description?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  statusLabel?: Maybe<Scalars['String']['output']>;
};

export type About = Node & Document & {
  __typename?: 'About';
  hudLabel?: Maybe<Scalars['String']['output']>;
  brandLabel?: Maybe<Scalars['String']['output']>;
  watermark?: Maybe<Scalars['String']['output']>;
  hero?: Maybe<AboutHero>;
  overview?: Maybe<AboutOverview>;
  vision?: Maybe<AboutVision>;
  manifesto?: Maybe<AboutManifesto>;
  footer?: Maybe<AboutFooter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  terminalText?: InputMaybe<StringFilter>;
};

export type AboutOverviewPathsFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  badge?: InputMaybe<StringFilter>;
};

export type AboutOverviewFilter = {
  quote?: InputMaybe<StringFilter>;
  paths?: InputMaybe<AboutOverviewPathsFilter>;
  bridgeText?: InputMaybe<StringFilter>;
};

export type AboutVisionFilter = {
  statement?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<StringFilter>;
};

export type AboutManifestoFilter = {
  watermark?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  lines?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
};

export type AboutFooterFilter = {
  description?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  statusLabel?: InputMaybe<StringFilter>;
};

export type AboutFilter = {
  hudLabel?: InputMaybe<StringFilter>;
  brandLabel?: InputMaybe<StringFilter>;
  watermark?: InputMaybe<StringFilter>;
  hero?: InputMaybe<AboutHeroFilter>;
  overview?: InputMaybe<AboutOverviewFilter>;
  vision?: InputMaybe<AboutVisionFilter>;
  manifesto?: InputMaybe<AboutManifestoFilter>;
  footer?: InputMaybe<AboutFooterFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type ContactNav = {
  __typename?: 'ContactNav';
  backLabel?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
};

export type ContactHero = {
  __typename?: 'ContactHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type ContactEmailCard = {
  __typename?: 'ContactEmailCard';
  label?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  copyLabel?: Maybe<Scalars['String']['output']>;
  copiedLabel?: Maybe<Scalars['String']['output']>;
};

export type ContactSocials = {
  __typename?: 'ContactSocials';
  name?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  nav?: Maybe<ContactNav>;
  hero?: Maybe<ContactHero>;
  emailCard?: Maybe<ContactEmailCard>;
  socialsTitle?: Maybe<Scalars['String']['output']>;
  socials?: Maybe<Array<Maybe<ContactSocials>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactNavFilter = {
  backLabel?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
};

export type ContactHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ContactEmailCardFilter = {
  label?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  copyLabel?: InputMaybe<StringFilter>;
  copiedLabel?: InputMaybe<StringFilter>;
};

export type ContactSocialsFilter = {
  name?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type ContactFilter = {
  nav?: InputMaybe<ContactNavFilter>;
  hero?: InputMaybe<ContactHeroFilter>;
  emailCard?: InputMaybe<ContactEmailCardFilter>;
  socialsTitle?: InputMaybe<StringFilter>;
  socials?: InputMaybe<ContactSocialsFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type HomeItemsStats = {
  __typename?: 'HomeItemsStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type HomeItems = {
  __typename?: 'HomeItems';
  id?: Maybe<Scalars['String']['output']>;
  tag?: Maybe<Scalars['String']['output']>;
  titleLines?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  imageSrc?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  detailHref?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<HomeItemsStats>>>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  items?: Maybe<Array<Maybe<HomeItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomeItemsStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type HomeItemsFilter = {
  id?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  titleLines?: InputMaybe<StringFilter>;
  imageSrc?: InputMaybe<ImageFilter>;
  description?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  detailHref?: InputMaybe<StringFilter>;
  stats?: InputMaybe<HomeItemsStatsFilter>;
};

export type HomeFilter = {
  items?: InputMaybe<HomeItemsFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateEntry: Entry;
  createEntry: Entry;
  updateAbout: About;
  createAbout: About;
  updateContact: Contact;
  createContact: Contact;
  updateHome: Home;
  createHome: Home;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateEntryArgs = {
  relativePath: Scalars['String']['input'];
  params: EntryMutation;
};


export type MutationCreateEntryArgs = {
  relativePath: Scalars['String']['input'];
  params: EntryMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};

export type DocumentUpdateMutation = {
  entry?: InputMaybe<EntryMutation>;
  about?: InputMaybe<AboutMutation>;
  contact?: InputMaybe<ContactMutation>;
  home?: InputMaybe<HomeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  entry?: InputMaybe<EntryMutation>;
  about?: InputMaybe<AboutMutation>;
  contact?: InputMaybe<ContactMutation>;
  home?: InputMaybe<HomeMutation>;
};

export type EntryMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  contentType?: InputMaybe<Scalars['String']['input']>;
  section?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  kicker?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  stack?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  status?: InputMaybe<Scalars['String']['input']>;
  repo?: InputMaybe<Scalars['String']['input']>;
  demo?: InputMaybe<Scalars['String']['input']>;
  highlights?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type AboutHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  terminalText?: InputMaybe<Scalars['String']['input']>;
};

export type AboutOverviewPathsMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
};

export type AboutOverviewMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  paths?: InputMaybe<Array<InputMaybe<AboutOverviewPathsMutation>>>;
  bridgeText?: InputMaybe<Scalars['String']['input']>;
};

export type AboutVisionMutation = {
  statement?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AboutManifestoMutation = {
  watermark?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  lines?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  quote?: InputMaybe<Scalars['String']['input']>;
};

export type AboutFooterMutation = {
  description?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  statusLabel?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMutation = {
  hudLabel?: InputMaybe<Scalars['String']['input']>;
  brandLabel?: InputMaybe<Scalars['String']['input']>;
  watermark?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<AboutHeroMutation>;
  overview?: InputMaybe<AboutOverviewMutation>;
  vision?: InputMaybe<AboutVisionMutation>;
  manifesto?: InputMaybe<AboutManifestoMutation>;
  footer?: InputMaybe<AboutFooterMutation>;
};

export type ContactNavMutation = {
  backLabel?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
};

export type ContactHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ContactEmailCardMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  copyLabel?: InputMaybe<Scalars['String']['input']>;
  copiedLabel?: InputMaybe<Scalars['String']['input']>;
};

export type ContactSocialsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  nav?: InputMaybe<ContactNavMutation>;
  hero?: InputMaybe<ContactHeroMutation>;
  emailCard?: InputMaybe<ContactEmailCardMutation>;
  socialsTitle?: InputMaybe<Scalars['String']['input']>;
  socials?: InputMaybe<Array<InputMaybe<ContactSocialsMutation>>>;
};

export type HomeItemsStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type HomeItemsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  titleLines?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  imageSrc?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  detailHref?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<HomeItemsStatsMutation>>>;
};

export type HomeMutation = {
  items?: InputMaybe<Array<InputMaybe<HomeItemsMutation>>>;
};

export type EntryPartsFragment = { __typename: 'Entry', title: string, date: string, summary: string, contentType: string, section?: string | null, category?: string | null, tag?: string | null, kicker?: string | null, author?: string | null, readTime?: string | null, coverImage?: string | null, tags: Array<string>, draft?: boolean | null, featured?: boolean | null, stack?: Array<string | null> | null, status?: string | null, repo?: string | null, demo?: string | null, highlights?: Array<string | null> | null, body?: any | null };

export type AboutPartsFragment = { __typename: 'About', hudLabel?: string | null, brandLabel?: string | null, watermark?: string | null, hero?: { __typename: 'AboutHero', eyebrow?: string | null, title?: Array<string | null> | null, terminalText?: string | null } | null, overview?: { __typename: 'AboutOverview', quote?: string | null, bridgeText?: string | null, paths?: Array<{ __typename: 'AboutOverviewPaths', eyebrow?: string | null, title?: string | null, description?: string | null, badge?: string | null } | null> | null } | null, vision?: { __typename: 'AboutVision', statement?: string | null, eyebrow?: string | null, paragraphs?: Array<string | null> | null } | null, manifesto?: { __typename: 'AboutManifesto', watermark?: string | null, intro?: string | null, lines?: Array<string | null> | null, quote?: string | null } | null, footer?: { __typename: 'AboutFooter', description?: string | null, ctaLabel?: string | null, statusLabel?: string | null } | null };

export type ContactPartsFragment = { __typename: 'Contact', socialsTitle?: string | null, nav?: { __typename: 'ContactNav', backLabel?: string | null, title?: string | null } | null, hero?: { __typename: 'ContactHero', eyebrow?: string | null, titleLine1?: string | null, titleLine2?: string | null, description?: string | null } | null, emailCard?: { __typename: 'ContactEmailCard', label?: string | null, email?: string | null, copyLabel?: string | null, copiedLabel?: string | null } | null, socials?: Array<{ __typename: 'ContactSocials', name?: string | null, desc?: string | null, url?: string | null } | null> | null };

export type HomePartsFragment = { __typename: 'Home', items?: Array<{ __typename: 'HomeItems', id?: string | null, tag?: string | null, titleLines?: Array<string | null> | null, imageSrc?: string | null, description?: string | null, ctaText?: string | null, detailHref?: string | null, stats?: Array<{ __typename: 'HomeItemsStats', value?: string | null, label?: string | null } | null> | null } | null> | null };

export type EntryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EntryQuery = { __typename?: 'Query', entry: { __typename: 'Entry', id: string, title: string, date: string, summary: string, contentType: string, section?: string | null, category?: string | null, tag?: string | null, kicker?: string | null, author?: string | null, readTime?: string | null, coverImage?: string | null, tags: Array<string>, draft?: boolean | null, featured?: boolean | null, stack?: Array<string | null> | null, status?: string | null, repo?: string | null, demo?: string | null, highlights?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EntryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EntryFilter>;
}>;


export type EntryConnectionQuery = { __typename?: 'Query', entryConnection: { __typename?: 'EntryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EntryConnectionEdges', cursor: string, node?: { __typename: 'Entry', id: string, title: string, date: string, summary: string, contentType: string, section?: string | null, category?: string | null, tag?: string | null, kicker?: string | null, author?: string | null, readTime?: string | null, coverImage?: string | null, tags: Array<string>, draft?: boolean | null, featured?: boolean | null, stack?: Array<string | null> | null, status?: string | null, repo?: string | null, demo?: string | null, highlights?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, hudLabel?: string | null, brandLabel?: string | null, watermark?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'AboutHero', eyebrow?: string | null, title?: Array<string | null> | null, terminalText?: string | null } | null, overview?: { __typename: 'AboutOverview', quote?: string | null, bridgeText?: string | null, paths?: Array<{ __typename: 'AboutOverviewPaths', eyebrow?: string | null, title?: string | null, description?: string | null, badge?: string | null } | null> | null } | null, vision?: { __typename: 'AboutVision', statement?: string | null, eyebrow?: string | null, paragraphs?: Array<string | null> | null } | null, manifesto?: { __typename: 'AboutManifesto', watermark?: string | null, intro?: string | null, lines?: Array<string | null> | null, quote?: string | null } | null, footer?: { __typename: 'AboutFooter', description?: string | null, ctaLabel?: string | null, statusLabel?: string | null } | null } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, hudLabel?: string | null, brandLabel?: string | null, watermark?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'AboutHero', eyebrow?: string | null, title?: Array<string | null> | null, terminalText?: string | null } | null, overview?: { __typename: 'AboutOverview', quote?: string | null, bridgeText?: string | null, paths?: Array<{ __typename: 'AboutOverviewPaths', eyebrow?: string | null, title?: string | null, description?: string | null, badge?: string | null } | null> | null } | null, vision?: { __typename: 'AboutVision', statement?: string | null, eyebrow?: string | null, paragraphs?: Array<string | null> | null } | null, manifesto?: { __typename: 'AboutManifesto', watermark?: string | null, intro?: string | null, lines?: Array<string | null> | null, quote?: string | null } | null, footer?: { __typename: 'AboutFooter', description?: string | null, ctaLabel?: string | null, statusLabel?: string | null } | null } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, socialsTitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav?: { __typename: 'ContactNav', backLabel?: string | null, title?: string | null } | null, hero?: { __typename: 'ContactHero', eyebrow?: string | null, titleLine1?: string | null, titleLine2?: string | null, description?: string | null } | null, emailCard?: { __typename: 'ContactEmailCard', label?: string | null, email?: string | null, copyLabel?: string | null, copiedLabel?: string | null } | null, socials?: Array<{ __typename: 'ContactSocials', name?: string | null, desc?: string | null, url?: string | null } | null> | null } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, socialsTitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav?: { __typename: 'ContactNav', backLabel?: string | null, title?: string | null } | null, hero?: { __typename: 'ContactHero', eyebrow?: string | null, titleLine1?: string | null, titleLine2?: string | null, description?: string | null } | null, emailCard?: { __typename: 'ContactEmailCard', label?: string | null, email?: string | null, copyLabel?: string | null, copiedLabel?: string | null } | null, socials?: Array<{ __typename: 'ContactSocials', name?: string | null, desc?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'HomeItems', id?: string | null, tag?: string | null, titleLines?: Array<string | null> | null, imageSrc?: string | null, description?: string | null, ctaText?: string | null, detailHref?: string | null, stats?: Array<{ __typename: 'HomeItemsStats', value?: string | null, label?: string | null } | null> | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'HomeItems', id?: string | null, tag?: string | null, titleLines?: Array<string | null> | null, imageSrc?: string | null, description?: string | null, ctaText?: string | null, detailHref?: string | null, stats?: Array<{ __typename: 'HomeItemsStats', value?: string | null, label?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export const EntryPartsFragmentDoc = gql`
    fragment EntryParts on Entry {
  __typename
  title
  date
  summary
  contentType
  section
  category
  tag
  kicker
  author
  readTime
  coverImage
  tags
  draft
  featured
  stack
  status
  repo
  demo
  highlights
  body
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  hudLabel
  brandLabel
  watermark
  hero {
    __typename
    eyebrow
    title
    terminalText
  }
  overview {
    __typename
    quote
    paths {
      __typename
      eyebrow
      title
      description
      badge
    }
    bridgeText
  }
  vision {
    __typename
    statement
    eyebrow
    paragraphs
  }
  manifesto {
    __typename
    watermark
    intro
    lines
    quote
  }
  footer {
    __typename
    description
    ctaLabel
    statusLabel
  }
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  nav {
    __typename
    backLabel
    title
  }
  hero {
    __typename
    eyebrow
    titleLine1
    titleLine2
    description
  }
  emailCard {
    __typename
    label
    email
    copyLabel
    copiedLabel
  }
  socialsTitle
  socials {
    __typename
    name
    desc
    url
  }
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  items {
    __typename
    id
    tag
    titleLines
    imageSrc
    description
    ctaText
    detailHref
    stats {
      __typename
      value
      label
    }
  }
}
    `;
export const EntryDocument = gql`
    query entry($relativePath: String!) {
  entry(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EntryParts
  }
}
    ${EntryPartsFragmentDoc}`;
export const EntryConnectionDocument = gql`
    query entryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EntryFilter) {
  entryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EntryParts
      }
    }
  }
}
    ${EntryPartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      entry(variables: EntryQueryVariables, options?: C): Promise<{data: EntryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EntryQueryVariables, query: string}> {
        return requester<{data: EntryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EntryQueryVariables, query: string}, EntryQueryVariables>(EntryDocument, variables, options);
      },
    entryConnection(variables?: EntryConnectionQueryVariables, options?: C): Promise<{data: EntryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EntryConnectionQueryVariables, query: string}> {
        return requester<{data: EntryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EntryConnectionQueryVariables, query: string}, EntryConnectionQueryVariables>(EntryConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  